### ISSUE TITLE
[Sample Product Documentation] (https://github.com/ProductHired/open-product-management/blob/master/README.md#sample-product-documentation) - Lynda Bitbucket links are wrong

### ISSUE THREAD

**Issue by PMKnaka** [ProductHired/open-product-management#86]
The links of Product Documentation about Lynda are wrong

Below are the correct ones

### Sample Product Documentation
....
[Global Lynda](https://leenau.bitbucket.io/lynda/product-requirements-document/) - Sample Product Requirements Document
[Global Lynda](https://leenau.bitbucket.io/lynda/user-personas/) - Sample Company Context and User Personas
[Global Lynda](https://leenau.bitbucket.io/lynda/metrics-case-study/) - Sample Metrics Case Study
[Global Lynda](https://leenau.bitbucket.io/lynda/language-rollout-phases/) - Sample Language Rollout Phases
[Global Lynda](https://leenau.bitbucket.io/lynda/go-to-market/) - Sample Go-to-Market Plan
....

The bitbucket link is ending with .org and should be .io

**Comment by tron1991** [comment]
It's resolved now @PMKnaka
